### ISSUE TITLE
Feature Request - Add support to ObjC Fixer also to binaries

### ISSUE THREAD

**Issue by weizenberg** [arandomdev/DyldExtractor#22]
You did awesome work on the objc_fixer, and I would like to use it also on the frameworks binaries, like on the **_accountsd_** binary. 

Currently, the **DyldExtractor** supports only framework extraction, adding a flag to import an extracted binary and running objc_fix over it would be an amazing feature.

**Comment by arandomdev** [comment]
I'm a bit confused,

If you're trying to get accountsd, and it's already in the cache, can't you just extract it?

otherwise, if accountsd is not in the cache, shouldn't disassemblers be able to process it? As all the information is there.

**Comment by weizenberg** [comment]
I extracted it manually, but sometimes the disassembler can't process the objc correctly, this is why I asked for this.

**Comment by arandomdev** [comment]
Can you explain how you manually extracted it?

also which device did you take it from

**Comment by weizenberg** [comment]
I used ssh client to scp the file to my computer, from iPhone 6s device running iOS 14.6

**Comment by arandomdev** [comment]
Sorry one last question, can you give me a few screenshots of your disassembler, and it’s output

**Comment by weizenberg** [comment]
Hey sorry for the delay. Attached screenshot from IDA (which successfully decrypted the other frameworks extracted using your code).  

![image](https://user-images.githubusercontent.com/2406418/130752569-ba1c4c9a-880f-4dfb-9a31-679d315dd720.png)

**Comment by arandomdev** [comment]
So I just disassembled it myself and got this for the functions and class list.
![image](https://user-images.githubusercontent.com/40927866/132080490-b1c7f333-600f-4b34-aa5c-091564e06fd0.png)

Like with a lot of Apple's daemons, it doesn't actually contain any ObjC classes of its own. It's just a starter for the Accounts.framework classes (check out the entry function). Because of this, objc_fixer.py won't do anything.

And besides, as I said above, binaries outside the cache should already have all the information it needs to run, and for disassemblers to make sense of it.
