### ISSUE TITLE
Out of range index in pageStarts

### ISSUE THREAD

**Issue by glen-mac** [arandomdev/DyldExtractor#23]
Just noting some bugs that popped up when running on an iOS 14.7.1 cache:

1. https://github.com/arandomdev/DyldExtractor/commit/39d6d91a8f09e34e78b230c938473076ddfa2d9e#diff-b9b14227a0f133e28dbb1e5ca1480fd4bc85aa9569131ae6037a9944e2b67fddR912 references `newAdrp` before it is defined. Same goes for `newLdr` a few lines below.

2. https://github.com/arandomdev/DyldExtractor/blob/master/src/DyldExtractor/converter/slide_info.py#L194: I have found some instances where the index `i` can be out of range of `pageStarts`.

Sorry haven't had the time to look into fixes, just thought i'd note them

**Comment by arandomdev** [comment]
It seems that the first bug was introduced in the fix for issue #21, I'm going to roll that commit back and try to come up with a better solution.

As for the second bug, can you provide the device identifier and ios version of your cache through [ispw.me](ipsw.me)? I'm been trying to track that bug down.

**Comment by glen-mac** [comment]
Sure, just grab the IPSW for iPhone11,4 14.7.1 18G82

**Comment by arandomdev** [comment]
fixed in 0e6a8342707b3a432db09121a61f4cc91730c6ee
